//Find
enum ESex
{
	SEX_MALE,
	SEX_FEMALE
};

///Add
#ifdef ENABLE_EXTEND_INVEN_SYSTEM
enum EInventory
{
	INVENTORY_OPEN_PAGE_COUNT = 2,//you can change
	INVENTORY_OPEN_KEY_VNUM = 72320,//you can change
	INVENTORY_WIDTH = 5,
	INVENTORY_HEIGHT = 9,
	INVENTORY_PAGE_SIZE = INVENTORY_WIDTH*INVENTORY_HEIGHT,
	INVENTORY_PAGE_COUNT = INVENTORY_MAX_NUM / INVENTORY_PAGE_SIZE,
	INVENTORY_OPEN_PAGE_SIZE = INVENTORY_OPEN_PAGE_COUNT*INVENTORY_PAGE_SIZE,
	INVENTORY_LOCKED_PAGE_COUNT = INVENTORY_PAGE_COUNT-INVENTORY_OPEN_PAGE_COUNT,
	INVENTORY_LOCK_COVER_COUNT = INVENTORY_LOCKED_PAGE_COUNT*INVENTORY_HEIGHT
};
#endif